-- Create episodes table
CREATE TABLE IF NOT EXISTS episodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meditation_id BIGINT REFERENCES meditations(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    image TEXT,
    media_type TEXT CHECK (media_type IN ('audio', 'video')),
    media_url TEXT,
    duration TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE episodes ENABLE ROW LEVEL SECURITY;

-- Public read access
CREATE POLICY "Allow public read access to episodes"
ON episodes FOR SELECT
TO public
USING (true);

-- Anonymous management (matching existing patterns in the project)
CREATE POLICY "Allow anonymous insert to episodes"
ON episodes FOR INSERT
TO anon
WITH CHECK (true);

CREATE POLICY "Allow anonymous update to episodes"
ON episodes FOR UPDATE
TO anon
USING (true);

CREATE POLICY "Allow anonymous delete to episodes"
ON episodes FOR DELETE
TO anon
USING (true);
